config/routes.rb
Rails.application.routes.draw do
  get '/index', to: 'homes#index'
  root 'homes#login'
  get '/about', to: 'homes#about'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/login', to: 'homes#login'
  resources :users
  resources :posts, only: [:new, :show, :create, :destroy], shallow: true do
  get :search, on: :collection
  resource :favorites, only: %i[create destroy]
  get :favorites, on: :collection
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, uniqueness: { scope: :post_id } # 追加
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  scope :desc, -> { order( created_at: :desc) }
  # default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 1000 }
  validates :title, presence: true, length: { maximum: 30 }
  validate :picture_size
  
  # postのお気に入り判定 → vies側で呼び出し
  def favorite_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  def self.search(search)
    return Post.all.desc unless search
    Post.where(['title LIKE ?', "%#{search}%"])
  end

  
  private
  
  # アップロードされた画像のサイズをバリデーションする
   def picture_size
     if picture.size > 5.megabytes
       errors.add(:picture, "5MB以下でお願いします")
     end
   end
   
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post
  validates :name, presence: true, length: { maximum: 20 }
  validates :description, length: { maximum: 150 }
  mount_uploader :picture, PictureUploader
  validate  :picture_size
  
   def self.find_or_create_from_auth(auth)
    provider = auth[:provider]
    uid = auth[:uid]
    nickname = auth[:info][:nickname]
    name = auth[:info][:name]
    image_url = auth[:info][:image]
    description = auth[:info][:description]
    
    self.find_or_create_by(provider: provider, uid: uid) do |user|
      user.nickname = nickname
      user.name = name
      user.image_url = image_url
      user.description = description
    end
   end
   
     private

    # アップロードされた画像のサイズをバリデーションする
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "5MB以下でお願いします")
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
    # beforeアクション
  private

    # ログイン済みユーザーかどうか確認
  def logged_in_user
    unless logged_in?
    flash[:danger] = "ログインしてください！"
      redirect_to login_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.build(post_id: params[:post_id])
    favorite.save!
    # flash[:success] = "お気に入り登録！"
    redirect_to request.referrer || root_url
  end

  def destroy
    current_user.favorites.find_by(post_id: params[:post_id]).destroy!
    # flash[:success] = "お気に入り解除！"
    redirect_to request.referrer || root_url
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def login
    if logged_in?
      @all_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(5).pluck(:post_id))
    end
  end
  
  
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action   :logged_in_user, only: [:new, :create, :destroy]
  before_action   :correct_user,   only: :destroy
  
  
  def new
    @post = current_user.posts.build
  end
  
  def show
    @post = Post.find_by(id: params[:id])
  end
  
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "投稿できました"
      redirect_to current_user
    else
      @feed_items = []
      render 'new'
    end
  end
  
  def destroy
   if @post.destroy
    flash[:success] = "削除しました"
    redirect_to  current_user
   else
    flash[:danger] = "削除に失敗しました"
    redirect_to request.referrer || root_url
   end
  end
  
  def search
    #Viewのformで取得したパラメータをモデルに渡す
    @posts = Post.search(params[:search]).paginate(page: params[:page]).desc
  end
  
  private
  
    def post_params
      params.require(:post).permit(:title, :content, :picture)
    end
    
    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to root_url if @post.nil?
    end
  
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def create
      user = User.find_or_create_from_auth(auth_params)
      if user
        log_in user
        flash[:success] = 'ログインしました'
        redirect_to user
      else
        flash[:danger] = 'ログインに失敗しました'
        redirect_to login_path
      end
    end

  def destroy
    reset_session
    flash[:success] = 'ログアウトしました'
    redirect_to root_path
  end  
  
    private
    # ユーザー情報の入った
    def auth_params
      request.env["omniauth.auth"]
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :corrent_user, only: [:edit, :update]
  # before_action :admin_user, only: :destroy
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def show
      @user = User.find_by(id: params[:id])
      @post = @user.posts.paginate(page: params[:page]).desc
      @posts = current_user.favorite_posts.includes(:user).paginate(page: params[:page]).desc
  end
  
  def edit
      @user = User.find(params[:id])
  end
  
  def update
      @user = User.find(params[:id])
        if @user.update_attributes(user_params)
          flash[:success] = "ユーザー情報を編集しました"
          redirect_to @user
        else
          render 'edit'
        end
  end
  
  def destroy
    User.find(params[:id]).destroy
    if current_user.admin? 
      flash[:success] = "削除しました！"
      redirect_to users_path
    else
      reset_session
      flash[:success] = "削除しました！"
      redirect_to root_path
    end
  end
  
  # beforeアクション
  
    # 正しいユーザーかどうか確認
  def corrent_user
    @user = User.find(params[:id])
    redirect_to login_path unless current_user?(@user)
  end
  
  
  private
    def user_params
        params.require(:user).permit(:name, :description, :picture)
    end
    
    # def admin_user
    #   redirect_to(root_path) unless current_user.admin?
    # end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    # ページごとの完全なタイトルを返します。
  def full_title(page_title = '')
    base_title = "Treasure -勉強投稿アプリ"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end
  
    # 渡されたユーザーがログイン済みユーザーであればtrueを返す
  def current_user?(user)
    user == current_user
  end
  
    # 現在ログイン中のユーザーを返す (いる場合)
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # 現在のユーザーをログアウトする
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/homes/about.html.erb
<% provide(:title, "Treasureについて")%>
<div class= "container">
  <div class= "row text-center">
    <div class= "col-12">
      <h1 class="display-4">Treasureについて</h1>
    </div>
    <hr>
    <div class="col-12">
      <p>Treasureは勉強したことを発信して情報共有するサービスです。</p>
      <div class= "image">
        <img src= "https://3.bp.blogspot.com/-LsO5L9qhYSM/U9y_Ur1kljI/AAAAAAAAjaw/Hq67ktTqOpM/s800/pasokon_kyoushitsu.png"　alt="勉強したこと共有の画像">
        <h2>勉強したことを共有</h2>
        <p>自分自身が勉強したことを発信することで多くの人に見てもらえ、モチベーションアップにつながります。</p>
        <p>また、他のユーザーの勉強したことも確認できます。</p>
        <p>自分に必要な情報であればお気に入りにをつけることもできます。</p>
      </div>
      
      <div class= "image">
        <img src= "https://1.bp.blogspot.com/-l7rOoye37i0/WtRzDyV-0zI/AAAAAAABLjk/pVDqZA2_NkUaP1dprAlMOX8nnfkdJu6IACLcBGAs/s800/kabu_chart_woman.png" alt="主な機能の画像">
        <h2>主な機能</h2>
        <p>勉強内容の登録、閲覧、編集
           ユーザー検索機能
           お気に入りユーザーのフォロー機能
        </p>
      </div>
      
      <div class= "image">
        <img src= "https://1.bp.blogspot.com/-L0IgETW-DVQ/WGnPOQXqP6I/AAAAAAABA1k/jv1PTrTvRXcRRcDUFVc4HvYpZ_N6Ah1LgCLcB/s800/computer_note_good.png"　alt="無料の画像">
        <h2>無料で利用可能</h2>
        <p>無料で全機能利用可能です。Twitterアカウントですぐにログインできます。</p>
      </div>

      <%= link_to "ログイン/新規登録", "/auth/twitter", method: :post, class: "btn btn-lg btn-primary about-btn" %>
    </div>
  </div>
</div>

app/views/homes/login.html.erb
<% if logged_in? %>
  <div class="row">
    <div class="col-md-9">
      <h3>ランキング (TOP5)</h3>
      <% if @all_ranks.any? %>
        <table class="table table-bordered border-primary table-hover table-sm posts_table">
          <thead class="thead-dark">
            <tr>
              <th scope="col" style="width: 400px">タイトル</th>
              <th scope="col" style="width: 150px">投稿者</th>
              <th scope="col" style="width: 150px">投稿日</th>
              <!--<th scope="col" style="width: 80px">削除</th>-->
            </tr>
          </thead>
          <%= render @all_ranks %>
        </table>
      <% end %>
    </div>
    
    <div class="col-md-3" id= "search">
      <p>投稿検索<p>
      <%= form_tag(search_posts_path,:method => 'get') do %>
      <%= text_field_tag :search %>
      <%= submit_tag '検索', :name => nil %>
      <% end %>
    </div>
  </div>
    


<% else %>

  <div class="center jumbotron">
    <h1>Treasure</h1>
    <h2>勉強したことを公開しよう！</h2>
    <%= link_to "ログイン/新規登録", "/auth/twitter", method: :post, class: "btn btn-lg btn-primary" %>
  </div>

<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    2020 かわうそ
  </small>
  <nav>
    <ul>
      <li><%= link_to "Treasureについて", about_path %></li>
      <li><a href= 'https://twitter.com/@kawauso0287' target= "_blank" rel= "noopener">運営者</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">

    <!-- 追記ここから-->
    <div class="navbar-header">

      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- 追記ここまで-->

      <%= link_to "Treasure", root_path, id: "logo" %>

    <!-- 追記ここから-->
    </div>
    <!-- 追記ここまで-->

    <nav>
      <!-- ulタグ内に「id="navbar"」を追記、classに「navbar-collapse collapse」を追記 -->
      <ul id="navbar" class="nav navbar-nav navbar-right navbar-collapse collapse">
            <li><%= link_to "トップ", root_path %></li>
          <% if logged_in? %>
            <li><%= link_to 'マイページ', current_user %></li>
            <li><%= link_to '投稿する', new_post_path %></li>
            <li><%= link_to 'ユーザー一覧', users_path %></li>
            <li><%= link_to 'ログアウト', logout_path %></li>
          <% else %>
            <li><%= link_to "Treasureについて", about_path %></li>
            <li><%= link_to "ログイン/新規登録", "/auth/twitter", method: :post %></li>
          <% end %>
      </ul>
    </nav>
  </div>
</header>



      
      
      

app/views/layouts/_shim.html.erb
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang= "ja">
  <head>
    <meta charset="utf-8">
	  <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= full_title(yield(:title)) %></title>
    <%= render "layouts/shim" %>
  </head>

  <body>
    <%= render "layouts/header"%>
    <div class= "container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer"%>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/posts/_post.html.erb
  <tbody>
    <tr>
      <th scope="row"><%= link_to post.title, post_path(post) %></th>
      <td><%= link_to post.user.name, post.user %></td>
      <td> <%= time_ago_in_words(post.created_at) %>前</td>
      <% if current_user?(post.user) %>
     <td> <%= link_to "削除", post, method: :delete,
                                data: { confirm: "本当に削除しますか?" } %></td>
    <% end %>
    </tr>
  </tbody>

app/views/posts/new.html.erb
<% provide(:title, "新規投稿") %>

<div class= "container">
  <div class="row">
    <div class="col-md-12">
      <h1>新規投稿</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class= "post">
        <%= form_for(@post) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
    
          <div class="post-new">
            <%= f.label :title %>
            <%= f.text_field :title, placeholder: "タイトルを記載してください", class: 'form-control' %>
          </div>
          
          <div class="post-new">
            <%= f.label :picture %>
            <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
          </div>
          
          <div class="post-new">
            <%= f.label :content %>
            <%= f.text_area :content, placeholder: "本文を記載してください", class: 'form-control', style: "height: 300px" %>
          </div>
          
          <div class= "delete-btn">
          <%= f.submit "投稿", class: "btn btn-primary" %>
          </div>
        <% end %>

        <script type="text/javascript">
          $('#post_picture').bind('change', function() {
          var size_in_megabytes = this.files[0].size/1024/1024;
          if (size_in_megabytes > 5) {
          alert('Maximum file size is 5MB. Please choose a smaller file.');}});
        </script>
      </div>
    </div>
  </div>
</div>

app/views/posts/search.html.erb
<% provide(:title, '検索結果') %>
<div class="row">
  <div class="col-12">
　  <h1>検索結果</h1>
　 </div>
</div>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
      <table class="table table-bordered border-primary table-hover table-sm posts_table">
        <thead class="thead-dark">
          <tr>
            <th scope="col" style="width: 400px">タイトル</th>
            <th scope="col" style="width: 150px">投稿者</th>
            <th scope="col" style="width: 150px">投稿日</th>
            <!--<th scope="col" style="width: 80px">削除</th>-->
          </tr>
        </thead>
        <%= render @posts %>
      </table>
      <%= will_paginate @posts %>
  </div>
</div>

app/views/posts/show.html.erb
<% provide(:title, "投稿詳細") %>

<div class= "row ">
  <div class= "col-md-12">
    <h1>投稿</h1>
  </div>
        <div class='favorite'>
    <% if !current_user?(@post.user) %>
    　<% if @post.favorite_by?(current_user) %> 
      　<%= link_to fa_icon("star 2x", text: "解除", class: "favorited"), post_favorites_path(@post.id), method: :delete %>
　　　<% else %>
  　　　　<%= link_to fa_icon("star 2x", text: "お気に入り",class: "favo") , post_favorites_path(@post.id), method: :post %>
    <% end %>
  <% end %>
  </div>
</div>
<div class= "row">
  <div class= "col-md-10 col-md-offset-1">
    <div class= "post-info">
      <table>
        <tr>
          <th>タイトル</th>
          <td><%= @post.title %></td>
        </tr>
        <tr>
          <th>投稿者</th>
          <td><%= @post.user.name %></td>
        </tr>
        <tr>
          <th>画像</th>
          <td><%= image_tag @post.picture.url if @post.picture? %></td>
        </tr>
        <tr>
          <th>本文</th>
          <td class="content"><%= @post.content %></td>
        </tr>
        <tr>
          <th>作成日</th>
          <td><%= time_ago_in_words(@post.created_at) %>前</td>
        </tr>
      </table>
    </div>
    <div class= "delete-btn">
      <% if current_user?(@post.user) %>
        <%= link_to "削除", @post, class: "btn btn-lg btn-primary", method: :delete, data: { confirm: "本当に削除しますか?" } %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
       <%= object.errors.count %>つの入力間違いがあります
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="posts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>


  <tbody>
    <tr>
      <th scope="row"><%= post.title %></th>
      <td><%= link_to post.user.name, post.user %></td>
      <td> <%= time_ago_in_words(post.created_at) %> ago.</td>
      <td><%= time_ago_in_words(post.updated_at) %> ago.</td>
    </tr>
  </tbody>

app/views/users/_show.html.erb
 <% if @user.posts.any? %>
<table class="table table-bordered border-primary table-hover table-sm posts_table" >
  <thead class="thead-dark">
    <tr>
      <th scope="col" style="width: 400px">タイトル</th>
      <th scope="col" style="width: 150px">投稿者</th>
      <th scope="col" style="width: 150px">投稿日</th>
      <!--<th scope="col" style="width: 80px">削除</th>-->
    </tr>
  </thead>
  <%= render @post %>
</table>
 <%= will_paginate @post %>
<% end %>

app/views/users/_show_favorite.html.erb
 <% if @posts.any? %>
  <table class="table table-bordered border-primary table-hover table-sm posts_table">
    <thead class="thead-dark">
      <tr>
        <th scope="col" style="width: 400px">タイトル</th>
        <th scope="col" style="width: 150px">投稿者</th>
        <th scope="col" style="width: 150px">投稿日</th>
        <!--<th scope="col" style="width: 80px">削除</th>-->
      </tr>
    </thead>
    <%= render @posts %>
  </table>
  <%= will_paginate @posts %>
<% end %>

app/views/users/_user.html.erb
<li>
  <% if user[:image_url] && user.picture.url %>
    <%= image_tag user.picture.url, size: '50x50' %>
    <% user[:image_url] = nil %>
  <% elsif user.picture.url %>
    <%= image_tag user.picture.url, size: '50x50' %>
  <% elsif user[:image_url] %>
    <%= image_tag( user[:image_url], alt:"image_url", size: '50x50') %>
  <% else %>
    <%= image_tag( "https://2.bp.blogspot.com/-BpXX9_8NFXQ/XDXcNPuKVSI/AAAAAAABRHw/nc0RoP5sRgg92x_vvfpfHeyulE5Gvm-wwCLcBGAs/s800/hair_innercolor.png", alt:"image_url", size: '50x50') %>
  <% end %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
  | <%= link_to "削除", user, method: :delete,data: {confirm: "削除しますか？"}%>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "プロフィール編集") %>
<h1>プロフィール編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <div class="post-new">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <div class="post-new">
        <%= f.label :description %>
        <%= f.text_field :description, class: 'form-control' %>
      </div>
      
      <div class="post-new">
        <%= f.label :picture %>
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
      </div>
　　　
　　　<div class= "delete-btn">
        <%= f.submit "変更", class: "btn btn-primary" %>
      </div>
    <% end %>
    
    <% if current_user?(@user) %>
      <%= link_to "(ユーザー情報削除)", @user,  method: :delete, data: { confirm: "本当に削除しますか?" } %>
    <% end %>
    
    <script type="text/javascript">
  $('#user_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('5MB以下でお願いします');
    }
  });
</script>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'ユーザー一覧') %>
<h1>ユーザー一覧</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>  
</ul>

<%= will_paginate %>

app/views/users/show.html.erb
<%= provide(:title, @user[:name] ) %>
<% if current_user?(@user) %>
<div class="row">
  <div class="col-12">
　  <h1>マイページ</h1>
　 </div>
</div>
<% end %>
<div class="row">
  <div class="col-md-3">
    <div class="user_info">
      <% if @user[:image_url] && @user.picture.url %>
        <%= image_tag @user.picture.url, size: '100x100' %>
        <% @user[:image_url] = nil %>
      <% elsif @user.picture.url %>
        <%= image_tag @user.picture.url, size: '100x100' %>
      <% elsif @user[:image_url] %>
        <%= image_tag( @user[:image_url], alt:"image_url", size: '100x100') %>
      <% else %>
        <%= image_tag( "https://2.bp.blogspot.com/-BpXX9_8NFXQ/XDXcNPuKVSI/AAAAAAABRHw/nc0RoP5sRgg92x_vvfpfHeyulE5Gvm-wwCLcBGAs/s800/hair_innercolor.png", alt:"image_url", size: '100x100') %>
      <% end %>
   
      <h4><%= @user[:name]%>
        <% if current_user?(@user) %>
          <small><%= link_to "(プロフィール編集)", edit_user_path(current_user) %> </small>
        <% end %>
      </h4>
    </div>
    <div class= "user-description">
      <p> <%= @user[:description]%> </p>
    </div>
  </div>
<div class="col-md-9">
  <ul class="nav nav-tabs" role="tablist">
    <li class="active" role="presentation">
      <a aria-controls="tab_a" data-toggle="tab" href="#tab_a" role="tab">投稿一覧(<%= @user.posts.count %>)</a>
    </li>
    <% if current_user?(@user) %>
    <li role="presentation">
      <a aria-controls="tab_b" data-toggle="tab" href="#tab_b" role="tab">お気に入り (<%= @posts.count %>)</a>
    </li>
    <% end %>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="tab_a" role="tabpanel">
      <%= render "users/show" %>
    </div>
    <% if current_user?(@user) %>
    <div class="tab-pane" id="tab_b" role="tabpanel">
  <%= render "users/show_favorite" %>
    </div>
    <% end %>
  </div>
</div>

  
</div>







 
 
 